# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: create new tag
        run: |
          time=$(date "+%Y%m%d")
          tag="test_tag"$time
          git tag $tag
          git push origin $tag
          git tag
          export TEST_TAG=tag

      - name: run regression test cases
        run: |
          resp=$(curl -X POST -H "'Content-type':'application/json','tesla-rm-token':'TCE_3d16a21b267556e1827190af97bdb25e'" -s -d '{"id": 81, "env": {"tag": $TEST_TAG}, "platform": "github actions", "user": "zhaoyinghui.qa"}' http://tesla.bytedance.net/rm/external/tasks/start)
          echo $resp


